/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import {
  createFileRoute,
  createRootRoute,
  lazyRouteComponent,
} from '@tanstack/svelte-router'

const rootRouteImport = createRootRoute()
const PostsRouteImport = createFileRoute('/posts')()
const AboutRouteImport = createFileRoute('/about')()
const IndexRouteImport = createFileRoute('/')()
const PostsIndexRouteImport = createFileRoute('/posts/')()
const PostsPostIdRouteImport = createFileRoute('/posts/$postId')()
const PostsPostIdIndexRouteImport = createFileRoute('/posts/$postId/')()
const PostsPostIdCommentsRouteImport = createFileRoute(
  '/posts/$postId/comments',
)()

const PostsRoute = PostsRouteImport.update({
  id: '/posts',
  path: '/posts',
  getParentRoute: () => rootRouteImport,
} as any).update({
  component: lazyRouteComponent(
    () => import('./routes/posts.svelte'),
    'default',
  ),
})
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any).update({
  component: lazyRouteComponent(
    () => import('./routes/about.svelte'),
    'default',
  ),
})
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any).update({
  component: lazyRouteComponent(
    () => import('./routes/index.svelte'),
    'default',
  ),
})
const PostsIndexRoute = PostsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PostsRoute,
} as any).update({
  component: lazyRouteComponent(
    () => import('./routes/posts.index.svelte'),
    'default',
  ),
})
const PostsPostIdRoute = PostsPostIdRouteImport.update({
  id: '/$postId',
  path: '/$postId',
  getParentRoute: () => PostsRoute,
} as any).update({
  component: lazyRouteComponent(
    () => import('./routes/posts.$postId.svelte'),
    'default',
  ),
})
const PostsPostIdIndexRoute = PostsPostIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PostsPostIdRoute,
} as any).update({
  component: lazyRouteComponent(
    () => import('./routes/posts.$postId/index.svelte'),
    'default',
  ),
})
const PostsPostIdCommentsRoute = PostsPostIdCommentsRouteImport.update({
  id: '/comments',
  path: '/comments',
  getParentRoute: () => PostsPostIdRoute,
} as any).update({
  component: lazyRouteComponent(
    () => import('./routes/posts.$postId/comments.svelte'),
    'default',
  ),
})

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/posts': typeof PostsRouteWithChildren
  '/posts/$postId': typeof PostsPostIdRouteWithChildren
  '/posts/': typeof PostsIndexRoute
  '/posts/$postId/comments': typeof PostsPostIdCommentsRoute
  '/posts/$postId/': typeof PostsPostIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/posts': typeof PostsIndexRoute
  '/posts/$postId/comments': typeof PostsPostIdCommentsRoute
  '/posts/$postId': typeof PostsPostIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/posts': typeof PostsRouteWithChildren
  '/posts/$postId': typeof PostsPostIdRouteWithChildren
  '/posts/': typeof PostsIndexRoute
  '/posts/$postId/comments': typeof PostsPostIdCommentsRoute
  '/posts/$postId/': typeof PostsPostIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/posts'
    | '/posts/$postId'
    | '/posts/'
    | '/posts/$postId/comments'
    | '/posts/$postId/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/about' | '/posts' | '/posts/$postId/comments' | '/posts/$postId'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/posts'
    | '/posts/$postId'
    | '/posts/'
    | '/posts/$postId/comments'
    | '/posts/$postId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  PostsRoute: typeof PostsRouteWithChildren
}

declare module '@tanstack/svelte-router' {
  interface FileRoutesByPath {
    '/posts': {
      id: '/posts'
      path: '/posts'
      fullPath: '/posts'
      preLoaderRoute: typeof PostsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/posts/': {
      id: '/posts/'
      path: '/'
      fullPath: '/posts/'
      preLoaderRoute: typeof PostsIndexRouteImport
      parentRoute: typeof PostsRoute
    }
    '/posts/$postId': {
      id: '/posts/$postId'
      path: '/$postId'
      fullPath: '/posts/$postId'
      preLoaderRoute: typeof PostsPostIdRouteImport
      parentRoute: typeof PostsRoute
    }
    '/posts/$postId/': {
      id: '/posts/$postId/'
      path: '/'
      fullPath: '/posts/$postId/'
      preLoaderRoute: typeof PostsPostIdIndexRouteImport
      parentRoute: typeof PostsPostIdRoute
    }
    '/posts/$postId/comments': {
      id: '/posts/$postId/comments'
      path: '/comments'
      fullPath: '/posts/$postId/comments'
      preLoaderRoute: typeof PostsPostIdCommentsRouteImport
      parentRoute: typeof PostsPostIdRoute
    }
  }
}

interface PostsPostIdRouteChildren {
  PostsPostIdCommentsRoute: typeof PostsPostIdCommentsRoute
  PostsPostIdIndexRoute: typeof PostsPostIdIndexRoute
}

const PostsPostIdRouteChildren: PostsPostIdRouteChildren = {
  PostsPostIdCommentsRoute: PostsPostIdCommentsRoute,
  PostsPostIdIndexRoute: PostsPostIdIndexRoute,
}

const PostsPostIdRouteWithChildren = PostsPostIdRoute._addFileChildren(
  PostsPostIdRouteChildren,
)

interface PostsRouteChildren {
  PostsPostIdRoute: typeof PostsPostIdRouteWithChildren
  PostsIndexRoute: typeof PostsIndexRoute
}

const PostsRouteChildren: PostsRouteChildren = {
  PostsPostIdRoute: PostsPostIdRouteWithChildren,
  PostsIndexRoute: PostsIndexRoute,
}

const PostsRouteWithChildren = PostsRoute._addFileChildren(PostsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  PostsRoute: PostsRouteWithChildren,
}
export const routeTree = rootRouteImport
  .update({
    component: lazyRouteComponent(
      () => import('./routes/__root.svelte'),
      'default',
    ),
  })
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
